apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: streaming-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
spec:
  selector:
    matchLabels:
      app: streaming-node
  replicas: 2
  template:
    metadata:
      labels:
        app: streaming-node
    spec:
      containers:
      - name: streaming-node
        image: streaming-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: 256Mi
              cpu: 500m
        volumeMounts:
          - mountPath: "/data"
            name: vod-volume
      volumes:
        - name: vod-volume
          hostPath:
              path: "/run/desktop/mnt/host/wsl/data"
---
apiVersion: v1
kind: Service
metadata:
  name: transcoding-service
spec:
  type: LoadBalancer
  ports:
  - port: 1935
    targetPort: 1935
  selector:
    app: transcoding-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoding-deployment
spec:
  selector:
    matchLabels:
      app: transcoding-node
  replicas: 1
  template:
    metadata:
      labels:
        app: transcoding-node
    spec:
      containers:
      - name: transcoding-node
        image: transcoding-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1935
        resources:
            limits:
              memory: 4Gi
              cpu: 6000m
        volumeMounts:
          - mountPath: "/data"
            name: vod-volume
      volumes:
        - name: vod-volume
          hostPath:
              path: "/run/desktop/mnt/host/wsl/data"