apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vod-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
spec:
  selector:
    matchLabels:
      app: streaming-node
  replicas: 7
  template:
    metadata:
      labels:
        app: streaming-node
    spec:
      containers:
      - name: streaming-node
        image: streaming-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
            limits:
              memory: 256Mi
              cpu: 150m
        volumeMounts:
          - mountPath: "/data"
            name: vod-volume
            readOnly: true
      volumes:
        - name: vod-volume
          persistentVolumeClaim:
            claimName: vod-pvc
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: streaming-node